#!/bin/bash
dw=""
waifu=""
function dep-check() {
    if command -v nala >/dev/null 2>&1; then
        sudo apt install nala -y
    fi
    if command -v dw >/dev/null 2>&1; then
        if command -v pipx >/dev/null 2>&1; then
            sudo nala install python3-full python3-pip pipx -y
        fi
        pipx install downloader-cli
        dw="~/.local/bin/dw"
    fi
    if command -v unzip >/dev/null 2>&1; then
        sudo nala install unzip -y
    fi
    if command -v ffmpeg >/dev/null 2>&1; then
        echo "ffmpeg is not installed, installing.."
        sudo nala install ffmpeg -y
    fi
    if command -v waifu2x-ncnn-vulkan >/dev/null 2>&1; then
        echo "waifu2x-ncnn-vulkan is not installed, installing.."
        if ! [ -d ~/Downloads ]; then
            mkdir ~/Downloads
        fi
        echo "Downloading the program.."
        $dw https://github.com/nihui/waifu2x-ncnn-vulkan/releases/download/20220728/waifu2x-ncnn-vulkan-20220728-ubuntu.zip ~/Downloads
        echo "Extraxting the program.."
        unzip ~/Downloads/waifu2x-ncnn-vulkan-20220728-ubuntu.zip -d ~/
        mv ~/waifu2x-ncnn-vulkan-20220728-ubuntu ~/waifu2x-ncnn-vulkan
        waifu=""
    fi
}
if [ -f "/etc/os-release" ]; then
    source /etc/os-release
    if [ -n "$ID" ]; then
        OS=$ID
        if ! [ $OS = "ubuntu" ]; then
            echo "The program only supports Ubuntu for now."
        else
            
        fi
    fi
fi
echo "Good bye!"